package tienda;
import javax.swing.*;
/*
*@author Osmar Guzman
*/

public class Menu extends javax.swing.JFrame {

    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Venta");
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JLabel();
        fondo1 = new javax.swing.JLabel();
        fondo6 = new javax.swing.JLabel();
        btSuma5 = new javax.swing.JButton();
        etCantidad5 = new javax.swing.JTextField();
        btResta5 = new javax.swing.JButton();
        fondo3 = new javax.swing.JLabel();
        MiTiendita = new javax.swing.JLabel();
        ivProducto1 = new javax.swing.JLabel();
        ivProducto2 = new javax.swing.JLabel();
        ivProducto3 = new javax.swing.JLabel();
        ivProducto4 = new javax.swing.JLabel();
        tAceiteVegetal = new javax.swing.JLabel();
        tLeche = new javax.swing.JLabel();
        tCola = new javax.swing.JLabel();
        tAtun = new javax.swing.JLabel();
        precio1 = new javax.swing.JLabel();
        precio2 = new javax.swing.JLabel();
        precio3 = new javax.swing.JLabel();
        precio4 = new javax.swing.JLabel();
        btSuma1 = new javax.swing.JButton();
        etCantidad1 = new javax.swing.JTextField();
        btResta1 = new javax.swing.JButton();
        btSuma2 = new javax.swing.JButton();
        etCantidad2 = new javax.swing.JTextField();
        btResta2 = new javax.swing.JButton();
        btSuma3 = new javax.swing.JButton();
        etCantidad3 = new javax.swing.JTextField();
        btResta3 = new javax.swing.JButton();
        btSuma4 = new javax.swing.JButton();
        etCantidad4 = new javax.swing.JTextField();
        btResta4 = new javax.swing.JButton();
        txtCantidad = new javax.swing.JLabel();
        txtCantidad1 = new javax.swing.JLabel();
        txtCantidad2 = new javax.swing.JLabel();
        txtCantidad3 = new javax.swing.JLabel();
        btCleanVenta = new javax.swing.JButton();
        btPagar = new javax.swing.JButton();
        btCerrarSesion = new javax.swing.JButton();
        fondo2 = new javax.swing.JLabel();
        ivProducto5 = new javax.swing.JLabel();
        ivProducto6 = new javax.swing.JLabel();
        txtCantidad4 = new javax.swing.JLabel();
        ivProducto7 = new javax.swing.JLabel();
        MiTiendita1 = new javax.swing.JLabel();
        iProducto5 = new javax.swing.JLabel();
        tHuevo = new javax.swing.JLabel();
        precio5 = new javax.swing.JLabel();
        btnResta5 = new javax.swing.JButton();
        ettCantidad5 = new javax.swing.JTextField();
        tAceiteVegetal1 = new javax.swing.JLabel();
        btnSuma5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtCantidad5 = new javax.swing.JLabel();
        iProducto7 = new javax.swing.JLabel();
        tAzucar = new javax.swing.JLabel();
        precio7 = new javax.swing.JLabel();
        btnResta7 = new javax.swing.JButton();
        ettCantidad7 = new javax.swing.JTextField();
        btnSuma7 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtCantidad6 = new javax.swing.JLabel();
        iProducto6 = new javax.swing.JLabel();
        tYogurt = new javax.swing.JLabel();
        precio6 = new javax.swing.JLabel();
        btnResta6 = new javax.swing.JButton();
        ettCantidad6 = new javax.swing.JTextField();
        btnSuma6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tCola4 = new javax.swing.JLabel();
        btResta9 = new javax.swing.JButton();
        etCantidad9 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        precio8 = new javax.swing.JLabel();
        txtCantidad7 = new javax.swing.JLabel();
        btSuma9 = new javax.swing.JButton();
        txtCantidad8 = new javax.swing.JLabel();
        iProducto8 = new javax.swing.JLabel();
        tCafe = new javax.swing.JLabel();
        precio9 = new javax.swing.JLabel();
        btnResta8 = new javax.swing.JButton();
        ettCantidad8 = new javax.swing.JTextField();
        btnSuma8 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/store.jpg"))); // NOI18N
        fondo.setText("jLabel3");

        fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/store.jpg"))); // NOI18N
        fondo1.setText("jLabel3");

        fondo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/store.jpg"))); // NOI18N
        fondo6.setText("jLabel3");

        btSuma5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btSuma5.setText("+");
        btSuma5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuma5ActionPerformed(evt);
            }
        });

        etCantidad5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etCantidad5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etCantidad5.setText("0");

        btResta5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btResta5.setText("-");
        btResta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResta5ActionPerformed(evt);
            }
        });

        fondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/store.jpg"))); // NOI18N
        fondo3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MiTiendita.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        MiTiendita.setForeground(new java.awt.Color(255, 255, 51));
        MiTiendita.setText("TIENDA - STORE");
        getContentPane().add(MiTiendita, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 22, 340, 40));

        ivProducto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aceite.jpg"))); // NOI18N
        getContentPane().add(ivProducto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 170, 170));

        ivProducto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/leche.jpg"))); // NOI18N
        getContentPane().add(ivProducto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 92, 170, 170));

        ivProducto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pescado.jpg"))); // NOI18N
        getContentPane().add(ivProducto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 92, 170, 170));

        ivProducto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresco.jpg"))); // NOI18N
        getContentPane().add(ivProducto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 92, 170, 170));

        tAceiteVegetal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tAceiteVegetal.setForeground(new java.awt.Color(255, 255, 255));
        tAceiteVegetal.setText("Aceite vegetal");
        getContentPane().add(tAceiteVegetal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        tLeche.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tLeche.setForeground(new java.awt.Color(255, 255, 255));
        tLeche.setText("Leche de vaca");
        getContentPane().add(tLeche, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        tCola.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tCola.setForeground(new java.awt.Color(255, 255, 255));
        tCola.setText("Refresco en lata");
        getContentPane().add(tCola, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, -1, -1));

        tAtun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tAtun.setForeground(new java.awt.Color(255, 255, 255));
        tAtun.setText("Atún en lata");
        getContentPane().add(tAtun, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, -1, -1));

        precio1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        precio1.setForeground(new java.awt.Color(255, 255, 0));
        precio1.setText("13000");
        getContentPane().add(precio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        precio2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        precio2.setForeground(new java.awt.Color(255, 255, 0));
        precio2.setText("9000");
        getContentPane().add(precio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));

        precio3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        precio3.setForeground(new java.awt.Color(255, 255, 0));
        precio3.setText("11500");
        getContentPane().add(precio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, -1, -1));

        precio4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        precio4.setForeground(new java.awt.Color(255, 255, 0));
        precio4.setText("7000");
        getContentPane().add(precio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, -1, -1));

        btSuma1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btSuma1.setText("+");
        btSuma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuma1ActionPerformed(evt);
            }
        });
        getContentPane().add(btSuma1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 50, 30));

        etCantidad1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etCantidad1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etCantidad1.setText("0");
        etCantidad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etCantidad1ActionPerformed(evt);
            }
        });
        getContentPane().add(etCantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 40, 30));

        btResta1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btResta1.setText("-");
        btResta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResta1ActionPerformed(evt);
            }
        });
        getContentPane().add(btResta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 40, 30));

        btSuma2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btSuma2.setText("+");
        btSuma2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuma2ActionPerformed(evt);
            }
        });
        getContentPane().add(btSuma2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 50, 30));

        etCantidad2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etCantidad2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etCantidad2.setText("0");
        getContentPane().add(etCantidad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 50, 30));

        btResta2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btResta2.setText("-");
        btResta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResta2ActionPerformed(evt);
            }
        });
        getContentPane().add(btResta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 50, 30));

        btSuma3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btSuma3.setText("+");
        btSuma3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuma3ActionPerformed(evt);
            }
        });
        getContentPane().add(btSuma3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 50, 30));

        etCantidad3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etCantidad3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etCantidad3.setText("0");
        getContentPane().add(etCantidad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 50, 30));

        btResta3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btResta3.setText("-");
        btResta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResta3ActionPerformed(evt);
            }
        });
        getContentPane().add(btResta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 50, 30));

        btSuma4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btSuma4.setText("+");
        btSuma4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuma4ActionPerformed(evt);
            }
        });
        getContentPane().add(btSuma4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 360, 50, 30));

        etCantidad4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etCantidad4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etCantidad4.setText("0");
        getContentPane().add(etCantidad4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 360, 50, 30));

        btResta4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btResta4.setText("-");
        btResta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResta4ActionPerformed(evt);
            }
        });
        getContentPane().add(btResta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 50, 30));

        txtCantidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(255, 255, 255));
        txtCantidad.setText("Cantidad");
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        txtCantidad1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCantidad1.setForeground(new java.awt.Color(255, 255, 255));
        txtCantidad1.setText("Cantidad");
        getContentPane().add(txtCantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, -1, -1));

        txtCantidad2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCantidad2.setForeground(new java.awt.Color(255, 255, 255));
        txtCantidad2.setText("Cantidad");
        getContentPane().add(txtCantidad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, -1, -1));

        txtCantidad3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCantidad3.setForeground(new java.awt.Color(255, 255, 255));
        txtCantidad3.setText("Cantidad");
        getContentPane().add(txtCantidad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 320, -1, -1));

        btCleanVenta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btCleanVenta.setText("Cancelar compra");
        btCleanVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCleanVentaActionPerformed(evt);
            }
        });
        getContentPane().add(btCleanVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 425, 170, 51));

        btPagar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btPagar.setText("Proceder al pago");
        btPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPagarActionPerformed(evt);
            }
        });
        getContentPane().add(btPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 425, 170, 51));

        btCerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btCerrarSesion.setText("Cerrar sesión");
        btCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 425, 170, 51));

        fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/store.jpg"))); // NOI18N
        fondo2.setText("jLabel3");
        getContentPane().add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 780, 480));

        ivProducto5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aceite.jpg"))); // NOI18N
        getContentPane().add(ivProducto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 92, 170, 170));

        ivProducto6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aceite.jpg"))); // NOI18N
        getContentPane().add(ivProducto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 170, 170));

        txtCantidad4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCantidad4.setForeground(new java.awt.Color(255, 255, 255));
        txtCantidad4.setText("Cantidad");
        getContentPane().add(txtCantidad4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 240, -1, -1));

        ivProducto7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aceite.jpg"))); // NOI18N
        getContentPane().add(ivProducto7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 170, 170));

        MiTiendita1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        MiTiendita1.setForeground(new java.awt.Color(255, 255, 51));
        MiTiendita1.setText("TIENDA - STORE");
        getContentPane().add(MiTiendita1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 22, 340, 40));

        iProducto5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/huevo.jpg"))); // NOI18N
        iProducto5.setText("jLabel1");
        getContentPane().add(iProducto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, 170, 160));

        tHuevo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tHuevo.setForeground(new java.awt.Color(255, 255, 255));
        tHuevo.setText("Huevo");
        getContentPane().add(tHuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 180, -1, 30));

        precio5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        precio5.setForeground(new java.awt.Color(255, 255, 0));
        precio5.setText("7000");
        getContentPane().add(precio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 200, -1, -1));

        btnResta5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnResta5.setText("-");
        btnResta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResta5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnResta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 270, 50, 30));

        ettCantidad5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ettCantidad5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ettCantidad5.setText("0");
        ettCantidad5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ettCantidad5ActionPerformed(evt);
            }
        });
        getContentPane().add(ettCantidad5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 270, 50, 30));

        tAceiteVegetal1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tAceiteVegetal1.setForeground(new java.awt.Color(255, 255, 255));
        tAceiteVegetal1.setText("Aceite vegetal");
        getContentPane().add(tAceiteVegetal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        btnSuma5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSuma5.setText("+");
        btnSuma5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuma5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSuma5, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 270, 50, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/store.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 210, 300));

        txtCantidad5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCantidad5.setForeground(new java.awt.Color(255, 255, 255));
        txtCantidad5.setText("Cantidad");
        getContentPane().add(txtCantidad5, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 550, -1, -1));

        iProducto7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/azucar.jpg"))); // NOI18N
        iProducto7.setText("jLabel1");
        getContentPane().add(iProducto7, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 320, 170, 170));

        tAzucar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tAzucar.setForeground(new java.awt.Color(255, 255, 255));
        tAzucar.setText("Azucar");
        getContentPane().add(tAzucar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 490, -1, 30));

        precio7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        precio7.setForeground(new java.awt.Color(255, 255, 0));
        precio7.setText("7000");
        getContentPane().add(precio7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 510, -1, -1));

        btnResta7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnResta7.setText("-");
        btnResta7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResta7ActionPerformed(evt);
            }
        });
        getContentPane().add(btnResta7, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 580, 50, 30));

        ettCantidad7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ettCantidad7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ettCantidad7.setText("0");
        ettCantidad7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ettCantidad7ActionPerformed(evt);
            }
        });
        getContentPane().add(ettCantidad7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 580, 50, 30));

        btnSuma7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSuma7.setText("+");
        btnSuma7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuma7ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSuma7, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 580, 50, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/store.jpg"))); // NOI18N
        jLabel6.setText("jLabel5");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 310, 210, 330));

        txtCantidad6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCantidad6.setForeground(new java.awt.Color(255, 255, 255));
        txtCantidad6.setText("Cantidad");
        getContentPane().add(txtCantidad6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 240, -1, -1));

        iProducto6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yogurt.jpg"))); // NOI18N
        iProducto6.setText("jLabel1");
        getContentPane().add(iProducto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 180, 160));

        tYogurt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tYogurt.setForeground(new java.awt.Color(255, 255, 255));
        tYogurt.setText("Yogurt");
        getContentPane().add(tYogurt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 180, -1, 30));

        precio6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        precio6.setForeground(new java.awt.Color(255, 255, 0));
        precio6.setText("7000");
        getContentPane().add(precio6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 200, -1, -1));

        btnResta6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnResta6.setText("-");
        btnResta6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResta6ActionPerformed(evt);
            }
        });
        getContentPane().add(btnResta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 270, 50, 30));

        ettCantidad6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ettCantidad6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ettCantidad6.setText("0");
        getContentPane().add(ettCantidad6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 270, 50, 30));

        btnSuma6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSuma6.setText("+");
        btnSuma6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuma6ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSuma6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 270, 50, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/store.jpg"))); // NOI18N
        jLabel7.setText("jLabel5");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, 210, 300));

        tCola4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tCola4.setForeground(new java.awt.Color(255, 255, 255));
        tCola4.setText("Huevo");
        getContentPane().add(tCola4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 180, -1, 30));

        btResta9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btResta9.setText("-");
        btResta9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResta9ActionPerformed(evt);
            }
        });
        getContentPane().add(btResta9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 270, 50, 30));

        etCantidad9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etCantidad9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etCantidad9.setText("0");
        getContentPane().add(etCantidad9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 270, 50, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/huevo.jpg"))); // NOI18N
        jLabel4.setText("jLabel1");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 20, 170, 160));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/store.jpg"))); // NOI18N
        jLabel8.setText("jLabel5");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, 210, 300));

        precio8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        precio8.setForeground(new java.awt.Color(255, 255, 0));
        precio8.setText("7000");
        getContentPane().add(precio8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 200, -1, -1));

        txtCantidad7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCantidad7.setForeground(new java.awt.Color(255, 255, 255));
        txtCantidad7.setText("Cantidad");
        getContentPane().add(txtCantidad7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 240, -1, -1));

        btSuma9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btSuma9.setText("+");
        btSuma9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuma9ActionPerformed(evt);
            }
        });
        getContentPane().add(btSuma9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 270, 50, 30));

        txtCantidad8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCantidad8.setForeground(new java.awt.Color(255, 255, 255));
        txtCantidad8.setText("Cantidad");
        getContentPane().add(txtCantidad8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 550, -1, -1));

        iProducto8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cafe2.jpg"))); // NOI18N
        iProducto8.setText("jLabel1");
        getContentPane().add(iProducto8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 320, 180, 170));

        tCafe.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tCafe.setForeground(new java.awt.Color(255, 255, 255));
        tCafe.setText("Cafe");
        getContentPane().add(tCafe, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 490, -1, 30));

        precio9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        precio9.setForeground(new java.awt.Color(255, 255, 0));
        precio9.setText("7000");
        getContentPane().add(precio9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 510, -1, -1));

        btnResta8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnResta8.setText("-");
        btnResta8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResta8ActionPerformed(evt);
            }
        });
        getContentPane().add(btnResta8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 580, 50, 30));

        ettCantidad8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ettCantidad8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ettCantidad8.setText("0");
        getContentPane().add(ettCantidad8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 580, 50, 30));

        btnSuma8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSuma8.setText("+");
        btnSuma8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuma8ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSuma8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 580, 50, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/store.jpg"))); // NOI18N
        jLabel10.setText("jLabel5");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 310, 210, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btResta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResta1ActionPerformed
        // TODO add your handling code here:
        Integer cantidad = Integer.parseInt(etCantidad1.getText());
        
        String resultado = String.valueOf(resta(cantidad));
       
        etCantidad1.setText(resultado);
    }//GEN-LAST:event_btResta1ActionPerformed

    private void btResta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResta2ActionPerformed
        // TODO add your handling code here:
        Integer cantidad = Integer.parseInt(etCantidad2.getText());
        
        String resultado = String.valueOf(resta(cantidad));
       
        etCantidad2.setText(resultado);
    }//GEN-LAST:event_btResta2ActionPerformed

    private void btResta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResta3ActionPerformed
        // TODO add your handling code here:
        Integer cantidad = Integer.parseInt(etCantidad3.getText());
        
        String resultado = String.valueOf(resta(cantidad));
       
        etCantidad3.setText(resultado);
    }//GEN-LAST:event_btResta3ActionPerformed

    private void btResta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResta4ActionPerformed
        // TODO add your handling code here:
        Integer cantidad = Integer.parseInt(etCantidad4.getText());
        
        String resultado = String.valueOf(resta(cantidad));
       
        etCantidad4.setText(resultado);
    }//GEN-LAST:event_btResta4ActionPerformed

    private void btSuma2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuma2ActionPerformed
        // TODO add your handling code here:
        Integer cantidad = Integer.parseInt(etCantidad2.getText());
        
        String resultado = String.valueOf(suma(cantidad));
       
        etCantidad2.setText(resultado);
    }//GEN-LAST:event_btSuma2ActionPerformed

    private void btPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPagarActionPerformed
        // TODO add your handling code here:
        
        String cantidad1= etCantidad1.getText();
        int c1 = Integer.parseInt(cantidad1);
        String cantidad2= etCantidad2.getText();
        int c2 = Integer.parseInt(cantidad2);
        String cantidad3= etCantidad3.getText();
        int c3 = Integer.parseInt(cantidad3);
        String cantidad4= etCantidad4.getText();
        int c4 = Integer.parseInt(cantidad4);
         String cantidad5= ettCantidad5.getText();
        int c5 = Integer.parseInt(cantidad5);
            String cantidad6= ettCantidad6.getText();
        int c6 = Integer.parseInt(cantidad6);
            String cantidad7= ettCantidad7.getText();
        int c7 = Integer.parseInt(cantidad7);
            String cantidad8= ettCantidad8.getText();
        int c8 = Integer.parseInt(cantidad8);
        
        if(c1==0 && c2==0 && c3==0 && c4==0){
            JOptionPane.showMessageDialog(null, "No hay articulos para pagar");
        }else{
            if(c1<0|| c2<0 || c3<0 || c4<0){
            JOptionPane.showMessageDialog(null, "NO PUEDES INGRESAR CANTIDADES NEGATIVAS");
            }else{
                this.setVisible(false);
                Detalle ventana3 = new Detalle();
        
                ventana3.cantidades(cantidad1, cantidad2, cantidad3, cantidad4);
                ventana3.setVisible(true);
            }
        
        
        }
        
        
        
    }//GEN-LAST:event_btPagarActionPerformed
    
    private void btSuma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuma1ActionPerformed
        // TODO add your handling code here:
        Integer cantidad = Integer.parseInt(etCantidad1.getText());
        
        String resultado = String.valueOf(suma(cantidad));
       
        etCantidad1.setText(resultado);
    }//GEN-LAST:event_btSuma1ActionPerformed

    private void btSuma3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuma3ActionPerformed
        // TODO add your handling code here:
        Integer cantidad = Integer.parseInt(etCantidad3.getText());
        
        String resultado = String.valueOf(suma(cantidad));
       
        etCantidad3.setText(resultado);
    }//GEN-LAST:event_btSuma3ActionPerformed

    private void btSuma4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuma4ActionPerformed
        // TODO add your handling code here:
        Integer cantidad = Integer.parseInt(etCantidad4.getText());
        
        String resultado = String.valueOf(suma(cantidad));
       
        etCantidad4.setText(resultado);
    }//GEN-LAST:event_btSuma4ActionPerformed

    private void etCantidad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etCantidad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etCantidad1ActionPerformed

    
    private void btCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCerrarSesionActionPerformed
        // TODO add your handling code here:
        Login ventana1 = new Login();
        this.setVisible(false);
    }//GEN-LAST:event_btCerrarSesionActionPerformed

    private void btCleanVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCleanVentaActionPerformed
        // TODO add your handling code here:
        etCantidad1.setText("0");
        etCantidad2.setText("0");
        etCantidad3.setText("0");
        etCantidad4.setText("0");
        ettCantidad5.setText("0");
        ettCantidad6.setText("0");
        ettCantidad7.setText("0");
        ettCantidad8.setText("0");
    }//GEN-LAST:event_btCleanVentaActionPerformed

    private void btSuma5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuma5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSuma5ActionPerformed

    private void btResta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResta5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btResta5ActionPerformed

    private void btnSuma5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuma5ActionPerformed
    // TODO add your handling code here:
        Integer cantidad = Integer.parseInt(ettCantidad5.getText());
        
        String resultado = String.valueOf(suma(cantidad));
       
        ettCantidad5.setText(resultado);
                                           // TODO add your handling code here:
    }//GEN-LAST:event_btnSuma5ActionPerformed

    private void btnResta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResta5ActionPerformed
        Integer cantidad = Integer.parseInt(ettCantidad5.getText());
        
        String resultado = String.valueOf(resta(cantidad));
       
        ettCantidad5.setText(resultado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnResta5ActionPerformed

    private void btnResta7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResta7ActionPerformed
          Integer cantidad = Integer.parseInt(ettCantidad7.getText());
        
        String resultado = String.valueOf(resta(cantidad));
       
        ettCantidad7.setText(resultado);    
    }//GEN-LAST:event_btnResta7ActionPerformed

    private void btnSuma7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuma7ActionPerformed
                                         
      Integer cantidad = Integer.parseInt(ettCantidad7.getText());
        
        String resultado = String.valueOf(suma(cantidad));
       
        ettCantidad7.setText(resultado);          // TODO add your handling code here:
    }//GEN-LAST:event_btnSuma7ActionPerformed

    private void btnResta6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResta6ActionPerformed
     // TODO add your handling code here:
        Integer cantidad = Integer.parseInt(ettCantidad6.getText());
        
        String resultado = String.valueOf(resta(cantidad));
       
        ettCantidad6.setText(resultado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnResta6ActionPerformed

    private void btnSuma6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuma6ActionPerformed
      Integer cantidad = Integer.parseInt(ettCantidad6.getText());
        
        String resultado = String.valueOf(suma(cantidad));
       
        ettCantidad6.setText(resultado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuma6ActionPerformed

    private void btResta9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResta9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btResta9ActionPerformed

    private void btSuma9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuma9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSuma9ActionPerformed

    private void btnResta8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResta8ActionPerformed
        Integer cantidad = Integer.parseInt(ettCantidad8.getText());
        
        String resultado = String.valueOf(resta(cantidad));
       
        ettCantidad8.setText(resultado); 
    }//GEN-LAST:event_btnResta8ActionPerformed

    private void btnSuma8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuma8ActionPerformed
                                       
      Integer cantidad = Integer.parseInt(ettCantidad8.getText());
        
        String resultado = String.valueOf(suma(cantidad));
       
        ettCantidad8.setText(resultado);  
    }//GEN-LAST:event_btnSuma8ActionPerformed

    private void ettCantidad7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ettCantidad7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ettCantidad7ActionPerformed

    private void ettCantidad5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ettCantidad5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ettCantidad5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    private int suma(int cantidad){
        cantidad = cantidad +1;        
        return cantidad;
    }
    private int resta(int cantidad){
        if(cantidad>0){
            cantidad = cantidad -1;
        }
        return cantidad;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MiTiendita;
    private javax.swing.JLabel MiTiendita1;
    private javax.swing.JButton btCerrarSesion;
    private javax.swing.JButton btCleanVenta;
    private javax.swing.JButton btPagar;
    private javax.swing.JButton btResta1;
    private javax.swing.JButton btResta2;
    private javax.swing.JButton btResta3;
    private javax.swing.JButton btResta4;
    private javax.swing.JButton btResta5;
    private javax.swing.JButton btResta9;
    private javax.swing.JButton btSuma1;
    private javax.swing.JButton btSuma2;
    private javax.swing.JButton btSuma3;
    private javax.swing.JButton btSuma4;
    private javax.swing.JButton btSuma5;
    private javax.swing.JButton btSuma9;
    private javax.swing.JButton btnResta5;
    private javax.swing.JButton btnResta6;
    private javax.swing.JButton btnResta7;
    private javax.swing.JButton btnResta8;
    private javax.swing.JButton btnSuma5;
    private javax.swing.JButton btnSuma6;
    private javax.swing.JButton btnSuma7;
    private javax.swing.JButton btnSuma8;
    private javax.swing.JTextField etCantidad1;
    private javax.swing.JTextField etCantidad2;
    private javax.swing.JTextField etCantidad3;
    private javax.swing.JTextField etCantidad4;
    private javax.swing.JTextField etCantidad5;
    private javax.swing.JTextField etCantidad9;
    private javax.swing.JTextField ettCantidad5;
    private javax.swing.JTextField ettCantidad6;
    private javax.swing.JTextField ettCantidad7;
    private javax.swing.JTextField ettCantidad8;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondo1;
    private javax.swing.JLabel fondo2;
    private javax.swing.JLabel fondo3;
    private javax.swing.JLabel fondo6;
    private javax.swing.JLabel iProducto5;
    private javax.swing.JLabel iProducto6;
    private javax.swing.JLabel iProducto7;
    private javax.swing.JLabel iProducto8;
    private javax.swing.JLabel ivProducto1;
    private javax.swing.JLabel ivProducto2;
    private javax.swing.JLabel ivProducto3;
    private javax.swing.JLabel ivProducto4;
    private javax.swing.JLabel ivProducto5;
    private javax.swing.JLabel ivProducto6;
    private javax.swing.JLabel ivProducto7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel precio1;
    private javax.swing.JLabel precio2;
    private javax.swing.JLabel precio3;
    private javax.swing.JLabel precio4;
    private javax.swing.JLabel precio5;
    private javax.swing.JLabel precio6;
    private javax.swing.JLabel precio7;
    private javax.swing.JLabel precio8;
    private javax.swing.JLabel precio9;
    private javax.swing.JLabel tAceiteVegetal;
    private javax.swing.JLabel tAceiteVegetal1;
    private javax.swing.JLabel tAtun;
    private javax.swing.JLabel tAzucar;
    private javax.swing.JLabel tCafe;
    private javax.swing.JLabel tCola;
    private javax.swing.JLabel tCola4;
    private javax.swing.JLabel tHuevo;
    private javax.swing.JLabel tLeche;
    private javax.swing.JLabel tYogurt;
    private javax.swing.JLabel txtCantidad;
    private javax.swing.JLabel txtCantidad1;
    private javax.swing.JLabel txtCantidad2;
    private javax.swing.JLabel txtCantidad3;
    private javax.swing.JLabel txtCantidad4;
    private javax.swing.JLabel txtCantidad5;
    private javax.swing.JLabel txtCantidad6;
    private javax.swing.JLabel txtCantidad7;
    private javax.swing.JLabel txtCantidad8;
    // End of variables declaration//GEN-END:variables
}
